
package ru.aparfenov.ws.soap.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MeetPointSoapWSImplService", targetNamespace = "http://soap.ws.aparfenov.ru/", wsdlLocation = "http://localhost:8080/meetpointws?wsdl")
public class MeetPointSoapWSImplService
    extends Service
{

    private final static URL MEETPOINTSOAPWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MEETPOINTSOAPWSIMPLSERVICE_EXCEPTION;
    private final static QName MEETPOINTSOAPWSIMPLSERVICE_QNAME = new QName("http://soap.ws.aparfenov.ru/", "MeetPointSoapWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/meetpointws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MEETPOINTSOAPWSIMPLSERVICE_WSDL_LOCATION = url;
        MEETPOINTSOAPWSIMPLSERVICE_EXCEPTION = e;
    }

    public MeetPointSoapWSImplService() {
        super(__getWsdlLocation(), MEETPOINTSOAPWSIMPLSERVICE_QNAME);
    }

    public MeetPointSoapWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MEETPOINTSOAPWSIMPLSERVICE_QNAME, features);
    }

    public MeetPointSoapWSImplService(URL wsdlLocation) {
        super(wsdlLocation, MEETPOINTSOAPWSIMPLSERVICE_QNAME);
    }

    public MeetPointSoapWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEETPOINTSOAPWSIMPLSERVICE_QNAME, features);
    }

    public MeetPointSoapWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MeetPointSoapWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MeetPointSoapWS
     */
    @WebEndpoint(name = "MeetPointSoapWSImplPort")
    public MeetPointSoapWS getMeetPointSoapWSImplPort() {
        return super.getPort(new QName("http://soap.ws.aparfenov.ru/", "MeetPointSoapWSImplPort"), MeetPointSoapWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MeetPointSoapWS
     */
    @WebEndpoint(name = "MeetPointSoapWSImplPort")
    public MeetPointSoapWS getMeetPointSoapWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.ws.aparfenov.ru/", "MeetPointSoapWSImplPort"), MeetPointSoapWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEETPOINTSOAPWSIMPLSERVICE_EXCEPTION!= null) {
            throw MEETPOINTSOAPWSIMPLSERVICE_EXCEPTION;
        }
        return MEETPOINTSOAPWSIMPLSERVICE_WSDL_LOCATION;
    }

}
