
package ru.aparfenov.ws.soap.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MeetPointSoapWS", targetNamespace = "http://soap.ws.aparfenov.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MeetPointSoapWS {


    /**
     * 
     * @return
     *     returns ru.aparfenov.ws.soap.api.MeetPointEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createMP", targetNamespace = "http://soap.ws.aparfenov.ru/", className = "ru.aparfenov.ws.soap.api.CreateMP")
    @ResponseWrapper(localName = "createMPResponse", targetNamespace = "http://soap.ws.aparfenov.ru/", className = "ru.aparfenov.ws.soap.api.CreateMPResponse")
    @Action(input = "http://soap.ws.aparfenov.ru/MeetPointSoapWS/createMPRequest", output = "http://soap.ws.aparfenov.ru/MeetPointSoapWS/createMPResponse")
    public MeetPoint createMP();

    /**
     * 
     * @param arg0
     * @return
     *     returns ru.aparfenov.ws.soap.api.MeetPointEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMP", targetNamespace = "http://soap.ws.aparfenov.ru/", className = "ru.aparfenov.ws.soap.api.GetMP")
    @ResponseWrapper(localName = "getMPResponse", targetNamespace = "http://soap.ws.aparfenov.ru/", className = "ru.aparfenov.ws.soap.api.GetMPResponse")
    @Action(input = "http://soap.ws.aparfenov.ru/MeetPointSoapWS/getMPRequest", output = "http://soap.ws.aparfenov.ru/MeetPointSoapWS/getMPResponse")
    public MeetPoint getMP(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns ru.aparfenov.ws.soap.api.MeetPointEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateMP", targetNamespace = "http://soap.ws.aparfenov.ru/", className = "ru.aparfenov.ws.soap.api.UpdateMP")
    @ResponseWrapper(localName = "updateMPResponse", targetNamespace = "http://soap.ws.aparfenov.ru/", className = "ru.aparfenov.ws.soap.api.UpdateMPResponse")
    @Action(input = "http://soap.ws.aparfenov.ru/MeetPointSoapWS/updateMPRequest", output = "http://soap.ws.aparfenov.ru/MeetPointSoapWS/updateMPResponse")
    public MeetPoint updateMP(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        MeetPoint arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteMP", targetNamespace = "http://soap.ws.aparfenov.ru/", className = "ru.aparfenov.ws.soap.api.DeleteMP")
    @ResponseWrapper(localName = "deleteMPResponse", targetNamespace = "http://soap.ws.aparfenov.ru/", className = "ru.aparfenov.ws.soap.api.DeleteMPResponse")
    @Action(input = "http://soap.ws.aparfenov.ru/MeetPointSoapWS/deleteMPRequest", output = "http://soap.ws.aparfenov.ru/MeetPointSoapWS/deleteMPResponse")
    public boolean deleteMP(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
